#!/bin/bash -x
declare -A result
read -p "Enter first number :: " a
read -p "Enter second number :: " b
read -p "Enter third number :: " c
result[1]=$(((a+b)*c))
result[2]=$(((a*b)+c))
result[3]=$((c+(a/b)))
result[4]=$(((a%b)+c))
